<?php 
$_helper = $this->helper('Blueskytechco\Themeoption\Helper\Product');
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
            <?php 
            $customTab = $_helper->getProductCustomTab();
            if(count($customTab) > 0){
                foreach($customTab as $custom_tab){
            ?>
            <div class="data item title"
                 data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($custom_tab['id']) ?>">
                <a class="data switch"
                   tabindex="-1"
                   data-toggle="trigger"
                   href="#<?= $block->escapeHtmlAttr($custom_tab['id']) ?>"
                   id="tab-label-<?= $block->escapeHtmlAttr($custom_tab['id']) ?>-title">
                    <?= /* @noEscape */ $custom_tab['title']; ?>
                </a>
            </div>
            <div class="data item content"
                 aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($custom_tab['id']) ?>-title" id="<?= $block->escapeHtmlAttr($custom_tab['id']) ?>" data-role="content">
                <?= $custom_tab['content'] ?>
            </div>
            <?php
                }
            }
            ?>
        </div>
    </div>
<?php endif; ?>
