<div class="header-container layout-1 layout-4">
	<?php if($block->isEnableTopBar()){ ?>
	<div class="topbar hidden-xs hidden-sticky">
		<div class="topbar__inner flex-layout space-between topbar__center_section center_vertical center-mobile container container_lager">
			<div class="topbar__section topbar__col-left topbar__static-text col-sm-5 col-top-link flex-layout center_vertical hidden-xxs no-wrap-desktop header__hotline">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_header_static_text')->toHtml(); ?> 
			</div>
			<div class="topbar__section topbar__col-right col-sm-7 col-top-link flex-layout center_vertical flex-end">
				<div class="topbar__locator">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_topbar_link_locator')->toHtml(); ?>
				</div>
				<div class="container-setting-language-currency">
					<?php echo $this->getChildHtml("store_language"); ?>  
					<?php echo $this->getChildHtml("currency"); ?> 
				</div>		
			</div>
		</div>
	</div>
	<?php } ?>
	<div class="header-content">
		<div class="container container_lager blueskytechco-header sub-menu-center">
			<div class="header_middle css_h_se  flex-layout space-between center_vertical flex-nowrap">
				<div class="header__left ">
					<div class="d-none d-xl-block">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_social_link')->toHtml(); ?>
					</div>
					<div data-action="toggle-nav" class="action nav-toggle d-xl-none sticky-toggle">
						<svg xmlns="http://www.w3.org/2000/svg" width="30" height="16" viewBox="0 0 30 16">
							<rect width="30" height="1.5"></rect>
							<rect y="7" width="20" height="1.5"></rect>
							<rect y="14" width="30" height="1.5"></rect>
						</svg>
					</div>
				</div>
				<div class="header__logo logo-container">
						<?php echo $this->getChildHtml('logo'); ?>
					
				</div>
				
				<div class="header__action col-right hidden_text flex-layout flex-end flex-nowrap">
					<div class="flex-layout center_vertical flex-end flex-nowrap">
						<?php echo $this->getChildHtml("rokan-search-autocomplete");?>
						<ul class="flex-layout header__action-default center_vertical no-wrap-desktop">
							<li class="account-link-header hidden-s">
								<?php echo $this->getChildHtml("header.links"); ?>
							</li>
							<?php echo $block->getLayout()->createBlock('Magento\Wishlist\Block\Link')->setTemplate('Magento_Wishlist::link.phtml')->toHtml();?>
							<li class="minicart-li-content-show-hide fixed-minicart">
								<?php echo $this->getChildHtml('minicart'); ?>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="header__menu border_true text-center sticky-header">
				<?php echo $this->getChildHtml("horizontal.menu"); ?>
			</div>
		</div>

	</div>
	
</div>