<?php
/**
 * Custom Catalog for store
 *
 * @var $viewModel \Blueskytechco\CustomCatalog\ViewModel\Catalog
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php 
    $_product = $block->getProduct();
    $view_model = $block->getViewModel();
?>
<?php 
if ( !$_product->isSaleable() ) {
    return;
}
$buttonTitle   = __('Add to Cart');
if ($_product->getTypeId() == 'bundle') {
    $buttonTitle = __('Customize and Add to Cart');
}
$_imageHelper  = $this->helper('Magento\Catalog\Helper\Image');
$imageUrl = $_imageHelper->init($_product, 'product_base_image')
    ->constrainOnly(TRUE)->keepAspectRatio(TRUE)
    ->keepTransparency(TRUE)->keepFrame(FALSE)->getUrl();
?>
<?php if ($view_model->getParamsProductSticky()) :?>
<div id="sticky-addcart" class="sticky-addcart">
    <div class="sticky_atc_wrap sticky_atc_shown">
        <div class="container">
            <div class="al_center fl_center">
                <div class="sticky_atc_content">
                    <div class="flex-layout no-gutters al_center">
                        <div class="col-auto sticky_atc_thumb flex al_center">
                            <div class="prd_stick-img" style="background-image: url(<?= $block->escapeHtmlAttr($imageUrl) ?>)"></div>
                            </div>
                        <div class="col sticky_atc_info">
                            <h4 class="product-name"><?= $block->escapeHtml($_product->getName()) ?></h4>
                            <div class="sticky_atc_price"><?= $block->getChildHtml('stickycart.product.price.final') ?></div>
                        </div>
                    </div>
                </div>
                <div class="sticky-action">
                    <div class="sticky-btn">
                        
                        <div class="quantity">
                            <a class="minus" href="#">
                                <i class="facl facl-minus"></i>
                            </a>
                            <div class="control">
                                <input type="number" class="input-text qty text tc js_sticky_qty" step="1" min="1" max="9999" name="quantity" value="1" size="4" pattern="[0-9]*">
                            </div>
                            <a class="plus" href="#">
                                <i class="facl facl-plus"></i>
                            </a>
                        </div>
                        <button class="single_add_to_cart_button button truncate sticky_atc_js">
                            <span><?= $block->escapeHtml($buttonTitle) ?></span>
                        </button>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>